
# 找不到节点
class NodeNotFindError ( Exception ) : ...

# 找不到边
class EdgeNotFindError ( Exception ) : ...

# 重复添加边
class EdgeRepeatError (Exception ) : ...

# 重复添加节点
class NodeRepeatError (Exception) : ...